language: python
python:
  - "3.7"
# command to install dependencies
install: "pip install --upgrade pip setuptools wheel && python setup.py develop"
# command to run tests
script: "python setup.py test"
# disable notification emails
notifications:
  email: false
