language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "python setup.py develop"
# command to run tests
script: "python setup.py test"
# disable notification emails
notifications:
  email: false
